foregrounds:
    diffuse_foreground:
        Tsky_mdl: 
            datafile: HERA_Tsky_Reformatted.npz
            interp_kwargs: {}
        omega_p:
            datafile: HERA_H2C_BEAM_MODEL.npz
            interp_kwargs:
                object: beam
                interpolator: interp1d
io:
    empty_uvdata:
        start_freq: 46920776.3671875
        channel_width: 122070.3125
        integration_time: 8.59
noise:
    _get_hera_bm_poly:
        datafile: HERA_H2C_BEAM_POLY.npy
    resample_Tsky:
        Tsky:  180.0
        mfreq:  0.18
        index:  -2.5
    sky_noise_jy:
        inttime:  8.59
    thermal_noise:
        Tsky_mdl:
            datafile: HERA_Tsky_Reformatted.npz
            interp_kwargs: {}
        omega_p:
            datafile: HERA_H2C_BEAM_MODEL.npz
            interp_kwargs:
                object: beam
                interpolator: interp1d
        Trx:  0
        inttime:  8.59
rfi:
    _get_hera_stations:
        datafile: HERA_H2C_RFI_STATIONS.npy
    rfi_impulse:
        chance:  0.001
        strength:  20.0
    rfi_scatter:
        chance:  0.0001
        strength:  10.0
        std:  10.0
    rfi_dtv:
        freq_min:  0.174
        freq_max:  0.214
        width:  0.008
        chance:  0.0001
        strength:  10.0
        strength_std:  10.0
sigchain:
    _get_hera_bandpass:
        datafile: HERA_H2C_BANDPASS.npy
    gen_bandpass:
        gain_spread:  0.1
    gen_whitenoise_xtalk:
        amplitude:  3.0
    gen_cross_coupling_xtalk:
        amp:  0.0
        dly:  0.0
        phs:  0.0

# XXX which of the above are functions that shouldn't be decorated by _defaults?
