diffuse_foreground:
    Tsky_mdl: !Tsky 
        datafile: HERA_Tsky_Reformatted.npz
        interp_kwargs: {}
    omega_p: !Beam
        datafile: HERA_H1C_BEAM_POLY.npy
        interp_kwargs:
            interpolator: poly1d

empty_uvdata:
    start_freq: !!float 1e8
    channel_width: 97656.25
    integration_time: 10.7

_get_hera_bm_poly:
    datafile: HERA_H1C_BEAM_POLY.npy

resample_Tsky:
    Tsky: 180.0
    mfreq: 0.18
    index: -2.5

sky_noise_jy:
    inttime: 10.7

thermal_noise:
    Tsky_mdl: !Tsky
        datafile: HERA_Tsky_Reformatted.npz
        interp_kwargs: {}
    omega_p: !Beam
        datafile: HERA_H1C_BEAM_POLY.npy
        interp_kwargs:
            interpolator: poly1d
    Trx: 0
    inttime: 10.7

_get_hera_stations:
    datafile: HERA_H1C_RFI_STATIONS.npy

rfi_impulse:
    chance: 0.001
    strength: 20.0

rfi_scatter:
    chance: 0.0001
    strength: 10.0
    std: 10.0

rfi_dtv:
    freq_min: 0.174
    freq_max: 0.214
    width: 0.008
    chance: 0.0001
    strength: 10.0
    strength_std: 10.0

_get_hera_bandpass:
    datafile: HERA_H1C_BANDPASS.npy
gen_bandpass:
    gain_spread: 0.1
gen_whitenoise_xtalk:
    amplitude: 3.0
gen_cross_coupling_xtalk:
    amp: 0.0
    dly: 0.0
    phs: 0.0

# XXX do we touch anything in utils, vis?
# XXX which of the above are functions that shouldn't be decorated by _defaults?
